### ISSUE TITLE
hello，请教一下，采集端也需要微信登录环境吗，我想改造一下，添加一套后端的登录逻辑，不想使用微信登录，目前对您的代码并没有进行深入阅读

### ISSUE THREAD

**Issue by phcbest** [Kw0k/NucleicAcidTest#2]

**Comment by phcbest** [comment]
后续我可能会改造支持硬件设备（esp8266）注册采集端节点或单位账号的功能，添加可选的微信或后台验证登录，不选择微信登录主要是目前申请微信开放平台的应用要准备一些材料，一些信息没法准备，干脆二次开发了

**Comment by Kw0k** [comment]
采集端是不许要微信登陆的，欢迎进行二次开发，我这项目当时写的比较仓促还有很多不完善的地方。
